### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTitle' of undefined

### ISSUE THREAD

**Issue by eistaa** [Kesin11/atom-vim-like-tab#1]
To reproduce:
1. Add a new vim-like-tab, do not add any thing to it.
2. Try to list the vim-like-tabs.

**Atom Version**: 1.7.4
**System**: Ubuntu 15.10
**Thrown From**: [atom-vim-like-tab](https://github.com/kesin11/atom-vim-like-tab) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getTitle' of undefined

```
At /home/eivinsaa/.atom/packages/atom-vim-like-tab/lib/tab_list_view.js:45

TypeError: Cannot read property 'getTitle' of undefined
    at /home/eivinsaa/.atom/packages/atom-vim-like-tab/lib/tab_list_view.js:45:66
    at Array.map (native)
    at TabListView.createItems (/home/eivinsaa/.atom/packages/atom-vim-like-tab/lib/tab_list_view.js:44:32)
    at TabListView.show (/home/eivinsaa/.atom/packages/atom-vim-like-tab/lib/tab_list_view.js:28:24)
    at atom-workspace.atomVimLikeTabList (/home/eivinsaa/.atom/packages/atom-vim-like-tab/lib/atom-vim-like-tab.js:25:64)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:15.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:15.1.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:15.1.0 atom-vim-like-tab:new (atom-text-editor.editor.vim-mode.normal-mode)
     -0:15.1.0 blur (atom-text-editor.editor.vim-mode.normal-mode)
     -0:11.9.0 command-palette:toggle (atom-pane.pane.active)
     -0:11.8.0 blur (atom-pane.pane.active)
     -0:06.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:06.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.3.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:06.3.0 atom-vim-like-tab:next (atom-pane.pane.active)
  2x -0:06.2.0 blur (atom-pane.pane)
     -0:04.6.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.3.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:01.0 atom-vim-like-tab:list (atom-text-editor.editor.vim-mode.normal-mode)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "automaticallyUpdate": false,
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "platformio-ide-terminal"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-material-ui",
      "material-monokai-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aligner, v0.22.0
atom-material-ui, v1.2.13
atom-ternjs, v0.14.1
atom-vim-like-tab, v1.0.0
autocomplete-python, v1.7.4
ex-mode, v0.8.0
highlight-selected, v0.11.2
imdone-atom, v1.3.29
keyboard-localization, v1.4.18
language-cmake, v0.1.4
language-cpp14, v0.6.1
language-doxygen, v0.2.1
language-latex, v0.6.1
line-diff-details, v1.3.5
linter, v1.11.4
linter-flake8, v1.13.0
material-monokai-syntax, v0.1.1
merge-conflicts, v1.4.3
minimap, v4.24.3
minimap-codeglance, v0.4.5
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.1
minimap-selection, v4.4.0
pigments, v0.29.1
release-notes, v0.53.0
sync-settings, v0.7.2
the-closer, v0.6.0
tool-bar, v0.4.0
tool-bar-main, v0.0.9
tree-view-git-status, v0.2.3
vim-mode, v0.65.1
vim-surround, v0.8.1
you-complete-me, v0.7.8

# Dev
No dev packages
```

**Comment by Kesin11** [comment]
@eistaa I merged #2 and publish v1.2.2
Thank you to report bug!
