### ISSUE TITLE
Error when switching tabs.

### ISSUE THREAD

**Issue by trusktr** [Kesin11/atom-vim-like-tab#12]
[Enter steps to reproduce:]

Make a new tab, open a file, then switch back to the first tab. Note, I had resotred a session with 3 normal Atom tabs, then I began attempting to use vim-like tabs.

So,

- when Atom opened, there were three existing Atom tabs.
- Then I made a new vim-like tab.
- Used cmd-p to open a file
- pressed `gT` (which I mapped to `atom-vim-like-tab:previous`)
- The error happened.

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [atom-vim-like-tab](https://github.com/kesin11/atom-vim-like-tab) package 1.5.1

### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:258

Error: Setting active pane that is not present in pane container
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:258:21)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:1018:46)
    at TabController.show (/packages/atom-vim-like-tab/lib/tab_controller.js:54:21)
    at AtomVimLikeTab.showTabByIndex (/packages/atom-vim-like-tab/lib/atom-vim-like-tab.js:92:43)
    at AtomVimLikeTab.showNextTab (/packages/atom-vim-like-tab/lib/atom-vim-like-tab.js:96:10)
    at HTMLElement.atomVimLikeTabNext (/packages/atom-vim-like-tab/lib/atom-vim-like-tab.js:31:44)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
  2x -0:56.1.0 vim-mode-plus:move-up (input.hidden-input)
     -0:54.5.0 atom-vim-like-tab:previous (input.hidden-input)
  4x -0:46 vim-mode-plus:move-up (input.hidden-input)
     -0:45.4.0 vim-mode-plus:activate-linewise-visual-mode (input.hidden-input)
  3x -0:45.3.0 vim-mode-plus:move-down (input.hidden-input)
     -0:44.4.0 vim-mode-plus:yank (input.hidden-input)
     -0:42.8.0 atom-vim-like-tab:next (input.hidden-input)
     -0:41.6.0 vim-mode-plus:put-before (input.hidden-input)
  3x -0:41.1.0 vim-mode-plus:move-down (input.hidden-input)
     -0:40.6.0 vim-mode-plus:insert-below-with-newline (input.hidden-input)
     -0:40.4.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:39.9.0 ex-mode:open (input.hidden-input)
     -0:39.7.0 core:confirm (input.hidden-input)
  3x -0:39.6.0 blur (input.hidden-input)
     -0:38.8.0 atom-vim-like-tab:next (input.hidden-input)
  4x -0:38.7.0 blur (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-browser 0.68.0 
atom-ide-ui 0.12.0 
atom-material-syntax 1.0.8 
atom-terminal-panel 4.4.4 
atom-vim-like-tab 1.5.1 
atom-webbrowser 2.1.4 
browser-plus 0.0.98 
ex-mode 0.18.0 
ex-mode-sort 1.0.0 
file-icons 2.1.21 
file-type-icons 1.3.4 
file-watcher 1.2.6 
hey-pane 1.1.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
ide-css 0.3.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-typescript 0.7.6 
ide-vue 0.1.8 
indent-guide-improved 1.4.13 
keymap-control 1.2.0 
keystroke 0.4.0 
language-pug 0.0.22 
language-vue 0.23.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-quick-highlight 1.0.1 
moonlight 0.7.0 
narrow 0.65.0 
narrow-git-ls 0.2.0 
one-tab 0.10.0 
open-this 0.5.0 
pane-browser 1.6.0 
paner 1.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
quick-highlight 0.13.0 
teletype 0.13.2 
terminal-plus 0.14.5 
terminal-tab 0.5.6 
toggle 0.6.2 
toggle-quotes 1.1.0 
tomorrow-night-eighties-syntax 1.0.2 
tree-view-git-status 1.5.0 
vim-mode-plus 1.32.0 
vim-mode-plus-ex-mode 0.11.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-macros 0.1.2 
vim-mode-plus-move-selected-text 0.12.0 
```

**Comment by Kesin11** [comment]
Thank you for your detailed error report!
But I'm sorry. I could not reproduce this error 🤔 

This is my environment.
Atom    : 1.28.1 (it is current stable atom version)
Electron: 2.0.4
Chrome  : 61.0.3163.100
Node    : 8.9.3
MacOSX: 10.13.5
atom-vim-like-tab: v1.5.1

I have no idea why this error occurd.
Can you retry it on newest stable atom version?
